config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

 devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :schools do
    collection { post :import
    post :fetch }

    resources :grades
    resources :survey
	  resources :ratings

    put :favorite, on: :member
  end

  resources :surveys do
    collection {
      post :import
    }
  end

  resources :grades do
    collection {
      post :import
    }
  end
  
  resources :search
  resources :browse

  root to: 'pages#home'
  get '/login' => 'pages#login'
  get '/admin' => 'schools#index'
  get '/socialmedia' => 'pages#socialmedia'
  get '/profile' => 'pages#profile'
  get '*path' => 'pages#home'

end

app/views/pages/admin.html.erb
<div ng-controller="AdminCtrl">
<!--
	<h1> Control Panel </h1>
	<%= button_to "Update From Server", fetch_schools_path %>
	<%= link_to 'Add School', new_school_path %><br>
  <%= link_to 'Edit School', controller: 'schools'%><br>
</div>
 <p>Import from file</p>
<%= form_tag import_schools_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Import" %>
<% end %>
<h2>Update from server</h2>
 -->

app/views/pages/home.html.erb
<div ng-controller="HomeCtrl">
	Welcome to Skoolr!<br/>
	</br>
	<div style="width: 700px; max-width: 100%;">
    Established in 2015, Skoolr is a website that provides various types of information on secondary schools in the Vancouver district (SD39). This idea was inspired by our own parents trying to determine which high school would be the best for us. Being informed about various schools is necessary for success and would be a huge factor for moving to new places especially with the increase in housing prices. We have provided a simple web application that allows you to search by school or address, and give information about the location, grades, and satisfaction survey results for each school. For convenience, visitors can create an account or sign in using Facebook. These users will have the ability to rate schools and save schools to their own ‘favourite’ page. If you have any questions or want to keep updated with the company, feel free to comment or tweet at us.<br/>
	</div>
	<br>
Thank You for visiting our website!<br/>

<br>
Sincerely,<br/>
Skoolr Development Team
 <br/>
	<div id="googleMap"></div>
</div>

app/views/pages/login.html.erb
<!--<div ng-controller="LoginCtrl">-->

<!--</div>-->
<div class = "button-row">
  <%= button_to "User login", new_user_session_path, class: "btn btn-primary"%>
  <%= button_to "Admin login", new_admin_session_path, class: "btn btn-primary" %>
</div>

app/views/pages/profile.erb
<h1>Favorites</h1>
<table>
  <% @favorites.each do |school| %>
    <tr><td><%= link_to school.name, browse_path(school.id) %></td></tr>
  <% end %>
</table>

<%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>

app/views/pages/search.html.erb
<div ng-controller="SearchCtrl">
	This is the search page. <br/>
	{{test}}
</div>

app/views/pages/socialmedia.html.erb
<div ng-controller="SocialmediaCtrl">
	<h1>Contact Information</h1>
	<div style="display: flex;">
		<div style="width: 300px;">
			Company Location: 2329 West Mall, Vancouver, BC V6T 1Z4
			</br>
			Email: Skoolr@gmail.com
			</br>
			Phone Number: 778-911-1111
		</div>
		<div>
			<div>
				Say something to us on facebook!
			</div>
			<div class="fb-comments" data-href="https://www.facebook.com/cpsc310skoolr" data-numposts="5"></div>
		</div>
		<div style="width: 500px;">
			<div>
				Follow us on twitter!
			</div>
			<div>
				<a class="twitter-timeline" href="https://twitter.com/ubcskoolr" data-widget-id="669135160785301504">Tweets by @ubcskoolr</a>
			</div>
		</div>
	</div>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>