config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

 devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :schools do
    collection { post :import
    post :fetch }

    resources :grades
    resources :survey
	  resources :ratings

    put :favorite, on: :member
  end

  resources :surveys do
    collection {
      post :import
    }
  end

  resources :grades do
    collection {
      post :import
    }
  end
  
  resources :search
  resources :browse

  root to: 'pages#home'
  get '/login' => 'pages#login'
  get '/admin' => 'schools#index'
  get '/socialmedia' => 'pages#socialmedia'
  get '/profile' => 'pages#profile'
  get '*path' => 'pages#home'

end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

	def index
		@schools = School.all
		if (params[:search])
			@schools = School.search(params[:search])
		else
			@schools = School.all
		end
	end

	def show
		@school = School.find(params[:id])
		@survey = @school.survey
		if (params[:search])
			@schools = School.search(params[:search])
		else
			@schools = School.all
		end
		render 'index'
	end
	

end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/views/browse/_show.html.erb
<div class="scroll-table" style="height:72vh;">
<h2> <%= @school.name %> </h2>

  <% if current_user %>
      <% if current_user.favorites.include?(@school) %>
          <%= link_to "unfavorite", favorite_school_path(@school, type: "unfavorite"), method: :put, class: "btn btn-primary" %><br>
      <% else %>
          <%= link_to "favorite",   favorite_school_path(@school, type: "favorite"), method: :put , class: "btn btn-primary" %><br>
      <% end %>
  <% end %>

<%= pluralize(@school.ratings.size, "user") %> 
rated this school
<% if @school.ratings.average(:value) != nil %>
	<%= @school.ratings.average(:value) %>/5.0
<% end %><br/>
<% if user_signed_in? && !admin_signed_in?%>
	<%= render "ratings/form" %>
<% else %>
	<br/>
<% end %>

<strong>Address:</strong> <br/> <%= @school.address %> <br/>
<br/><strong>Grades:</strong> <br/> 
<% @school.grades.each do |grade| %>
	<span class="graph" style="padding: 0 0 0 <%= grade.average_mark %>px"> <%= grade.average_mark %> </span> <%= grade.subject %> <br/>
<% end %>
<% if @survey != nil %>
<br/><strong>Surveys:</strong> <br/> 
<table id="surveyTable">
<tr>
<th>Total responses</th><th>Very satisfied</th><th>Somewhat satisfied</th><th>Neither satisifed nor dissatisfied</th><th>Dissatisfied</th>
</tr>
	<tr>
		<td><%= @survey.many_or_all_responses + @survey.at_no_time_responses + @survey.few_times_responses + @survey.some_times_responses%></td> <td><%= @survey.many_or_all_responses %></td> <td><%= @survey.some_times_responses %></td> <td><%= @survey.few_times_responses %></td> <td><%= @survey.at_no_time_responses %></td>
	</tr>
</table> 
<% end %>
<script>generateMap('<%= @school.address %>')</script>
<div id="googleMap"></div>

<div>
<a class="twitter-timeline" href="https://twitter.com/VSB39" data-widget-id="669735318787002368">Tweets by @VSB39</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
</div>

app/views/browse/index.html.erb
<div ng-controller="BrowseCtrl">
	<!--
	<div class="height-80vh boxed col-md-6">
		<form><input class="font-24 width-100p" ng-change="schoolSearch()" ng-model="searchQuery" placeholder="Search"></input></form><br/>
		<select class="font-24 width-100p" style="height:90%;" size="2">
			<option ng-repeat="school in searchResults | orderBy: 'name'" ng-click="loadSchoolInfo(school.id)">
				{{school.name}}
			</option>
		</select>
	</div>
	
	<div class="height-80vh boxed col-md-6">
		<span ng-show="schoolName">
			<h2> {{schoolName}}</h2>
			<strong>Address:</strong> <br/> {{schoolAddress}}<br/>
			<br/><strong>Grades (subject, grade, average mark):</strong> <br/> 
			<div ng-repeat="grade in schoolGrades">
				<span class="graph" style="padding:0 0 0 {{grade.average_mark}}px;"> {{grade.average_mark}} </span> {{grade.subject}} {{grade.grade}}
			</div>
			<br/><strong>Surveys:</strong> <br/> 
			<option ng-repeat="survey in schoolSurveys">
				{{survey.question}}, {{survey.non_excluded_responses}}, {{survey.many_or_all_responses}}, {{survey.at_no_time_responses}}, {{survey.few_times_responses}}, {{survey.some_times_responses}}
			</option>
			<div id="googleMap"></div>
		</span>
	</div>
	-->
	<div class="height-80vh boxed col-md-6">
			<%= form_tag(browse_index_path, :method => "get") do %>
				<%= text_field_tag :search, params[:search], placeholder: "Search", class: "font-24 width-100p" %>
			<% end %>
		<div class="scroll-table" style="height:72vh;">
			<% @schools.sort_by {|h| h[:name]}.each do |school| %>
				<%= link_to school.name, browse_path(school, :search => params[:search]), class: "font-24 width-100p btn btn-default", style: "text-align:left;" %>
			<% end %>
		</div>
	</div>
	
	<div class="height-80vh boxed col-md-6">
		<% if !current_page?(:controller => "browse") %>
			<%= render partial: "show" %>
		<% end %>
	</div>
</div>