config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

 devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :schools do
    collection { post :import
    post :fetch }

    resources :grades
    resources :survey
	  resources :ratings

    put :favorite, on: :member
  end

  resources :surveys do
    collection {
      post :import
    }
  end

  resources :grades do
    collection {
      post :import
    }
  end
  
  resources :search
  resources :browse

  root to: 'pages#home'
  get '/login' => 'pages#login'
  get '/admin' => 'schools#index'
  get '/socialmedia' => 'pages#socialmedia'
  get '/profile' => 'pages#profile'
  get '*path' => 'pages#home'

end

app/models/school.rb
class School < ActiveRecord::Base
  require 'open-uri'

  has_many :favorite_schools
  has_many :favorited_by, through: :favorite_schools, source: :user
  has_many :ratings, dependent: :destroy
  has_many :grades, dependent: :destroy
  has_one :survey, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  
  geocoded_by :address
  after_validation :geocode

  def self.import(file)
    xls = Roo::Spreadsheet.open(file, extension: :xls)
    xls.each(name: 'SCHOOL_NAME', address: 'ADDRESS') do |hash|
      if valid?(hash)
        school = School.create(name: hash[:name].split(' ')[0...-1].join(' '), address: hash[:address] + " Vancouver")
		school.create_survey(school_id: school.id, many_or_all_responses: 0, at_no_time_responses: 0, few_times_responses: 0, some_times_responses: 0)
      end
    end
  end

  def self.fetch
    f = open("ftp://webftp.vancouver.ca/OpenData/xls/schools.xls")
    import(f)
  end
  
  def self.search(query)
	where('name LIKE ?', "%" + query + "%").all
  end
  
  def self.searchNearby(query)
	where('self.distance_to(query) < 5').all
  end

  private
  def self.valid?(hash)
    return !School.exists?(name: hash[:name].split(' ')[0...-1].join(' ')) && hash[:name] != "SCHOOL_NAME" && hash[:name].split.last.delete('.') == "Sec"
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

	def index
		@schools = School.all
	end

	def show
		@school = School.find(params[:id])
		@survey = @school.survey
	end

	def new
		@school = School.new
	end

	def edit
		@school = School.find(params[:id])
	end

	def create
		@school = School.new(school_params)
		@school.create_survey(school_id: @school.id, many_or_all_responses: 0, at_no_time_responses: 0, few_times_responses: 0, some_times_responses: 0)
		if @school.save
			redirect_to @school
		else
			render 'new'
		end
	end

	def update
		@school = School.find(params[:id])

		if @school.update(school_params)
			redirect_to @school
		else
			render 'edit'
		end
	end

	def destroy
		@school = School.find(params[:id])
		@school.destroy

		redirect_to schools_path
	end

	def import
		School.import(params[:file])
		redirect_to schools_path, notice: "Schools imported."
	end

	def fetch
		School.fetch
		redirect_to schools_path, notice: "Schools imported."
	end

	def favorite
		type = params[:type]
		school = School.find(params[:id])
		if type == "favorite"
			if current_user.favorites.include?(school)
				redirect_to :back
			else
				current_user.favorites << school
				redirect_to :back, notice: "You favorited #{school.name}"
			end

		elsif type == "unfavorite"
			current_user.favorites.delete(school)
			redirect_to :back, notice: "Unfavorited #{school.name}"

		else
			redirect_to :back, notice: "Shouldn't get here"
		end
	end

	private
		def school_params
			params.require(:school).permit(:name, :address)
		end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.erb
<%= form_for @school do |f| %>

    <% if @school.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@school.errors.count, "error") %> prohibited
            this school from being saved:
          </h2>
          <ul>
            <% @school.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/schools/edit.erb
<h1>Edit school</h1>

<%= render 'schools/form' %>

<h2>Add grade:</h2>

<%= render 'grades/form' %>

<% if @school.survey != nil %>
<h2>Edit survey:</h2>
<%= render 'surveys/form' %>
<% end %>

app/views/schools/index.erb
<h2>Manage Schools</h2>
<div class="button-row">
  <%= button_to "Update schools from server", fetch_schools_path, class: "btn btn-primary" %>
  <%= button_to "Add school manually", new_school_path, :method => :get, class: "btn btn-primary" %>
  <%= button_to "Add survey data", import_surveys_path, class: "btn btn-primary" %>
  <%= button_to "Add grades data", import_grades_path, class: "btn btn-primary" %>
</div><br/>
<div class="media scroll-table height-70vh">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>School Name</th>
          <th>Address</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

	<tbody>
	  <% @schools.each do |school| %>
	  <tr>
		<td><%= link_to "", school_path(school), class: "glyphicon glyphicon-search" %> <%= school.name %></td>
		<td><%= school.address %></td>
		<td><%= link_to "", edit_school_path(school), class: "glyphicon glyphicon-pencil" %></td>
		<td><%= link_to "", school_path(school),
				method: :delete,
				data: { confirm: "Are you sure?" },
				class: "glyphicon glyphicon-trash" %></td>
	  </tr>
	  <% end %>
	</tbody>
</table>
</div>
</div>

app/views/schools/new.html.erb
<h1>Add school</h1>

<%= render 'form' %>

app/views/schools/show.erb
<p>
  <strong><%= @school.name %></strong>
</p>
<p>
  <%= @school.address %>
</p>
<h2>Grades</h2>
<% @school.grades.each do |grade| %>
  <p>
    <strong>Subject</strong>
    <%= grade.subject %>
  </p>
  <p>
    <strong>Average mark</strong>
    <%= grade.average_mark %>
  </p>
  
  <p>
    <%= link_to 'Destroy Grade', [grade.school, grade],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>
<% if @survey != nil %>
<h2>Surveys</h2>
  <p>
    <strong>Very satisfied</strong>
    <%= @survey.many_or_all_responses %>
  </p>
  <p>
    <strong>Somewhat satisfied</strong>
    <%= @survey.some_times_responses %>
  </p>
  <p>
    <strong>Neither satisifed nor dissatisfied</strong>
    <%= @survey.few_times_responses %>
  </p>
  <p>
    <strong>Dissatisfied</strong>
    <%= @survey.at_no_time_responses %>
  </p>
<% end %>